name: Release

on:
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: audio-share-app
    steps:
    - uses: actions/checkout@v3
    - run: cd audio-share-app
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - run: chmod +x gradlew
    - run: ./gradlew :app:assembleRelease
    - run: sed -En 's/\s*versionName\s+"([^"]*)"/version=\1/p' app/build.gradle >> $GITHUB_OUTPUT
      id: get_version
      
  build_server:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: audio-share-server
    steps:
    - uses: actions/checkout@v3
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: 6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2
    - run: vcpkg integrate install
    - run: vcpkg install asio:x64-windows-static-md protobuf:x64-windows-static-md spdlog:x64-windows-static-md
    - run: msbuild /m /p:Configuration=Release
    
  # release:
  #   runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    # - run: gh release create "v$VERSION" -t "v$VERSION" app/build/outputs/apk/release/*.apk
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     VERSION: ${{ steps.get_version.outputs.version }}
