name: Release

on:
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: audio-share-app
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      version_code: ${{ steps.get_version_code.outputs.version_code }}
      hash: ${{ steps.get_hash.outputs.hash }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Create relese.jks
      run: mkdir ~/.android && echo "$release_jks" | base64 -d > ~/.android/release.jks
      env:
        release_jks: ${{ secrets.RELEASE_JKS }}
    - name: Create keystore.properties
      run: echo -e "storeFile=$(ls ~/.android/release.jks)\nstorePassword=${store_pass}\nkeyAlias=${key_alias}\nkeyPassword=${key_pass}\n" > keystore.properties
      env:
        store_pass: ${{ secrets.STORE_PASS }}
        key_alias: ${{ secrets.KEY_ALIAS }}
        key_pass: ${{ secrets.KEY_PASS }}
        
    - run: chmod +x gradlew
    - run: ./gradlew :app:assembleRelease
    - run: ./gradlew :app:signingReport
    
    - name: Get versionName
      run: sed -En 's/versionName\s*=\s*"([^"]*)"/version=\1/p' app/build.gradle.kts | tee $GITHUB_OUTPUT
      id: get_version
    
    - name: Get versionCode
      run: sed -En 's/versionCode\s*=\s*([0-9]*)/version_code=\1/p' app/build.gradle.kts | tee $GITHUB_OUTPUT
      id: get_version_code

    - uses: actions/upload-artifact@v3
      with:
        name: app
        path: audio-share-app/app/build/outputs/apk/release/*.apk
        
    - name: Get sha256sum
      run: sha256sum app/build/outputs/apk/release/*.apk | awk '{ printf "hash=%s", $1 }' | tee $GITHUB_OUTPUT
      id: get_hash
      
  build_server:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: audio-share-server
    outputs:
      hash: ${{ steps.get_hash.outputs.hash }}
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msbuild@v1
    - uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: 9edb1b8e590cc086563301d735cae4b6e732d2d2
    - run: vcpkg integrate install
    - run: vcpkg install asio:x64-windows-static-md protobuf:x64-windows-static-md spdlog:x64-windows-static-md
    - run: msbuild /m /p:Configuration=Release,Platform=x64
    - uses: actions/upload-artifact@v3
      with:
        name: server
        path: audio-share-server/x64/Release/*.exe
    - name: Get sha256num
      run: sha256sum x64/Release/*.exe | awk '{ printf "hash=%s", $1 }' | tee $GITHUB_OUTPUT
      id: get_hash
      shell: bash
    
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [ build_app, build_server ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v2
      with:
        name: app
    - uses: actions/download-artifact@v2
      with:
        name: server
    - name: Generate release notes
      run: 'echo -e "$(cat ../metadata/en-US/changelogs/${version_code}.txt)\n---\nsha256sum:\n$(ls *.apk): ${app_hash}\n$(ls *.exe): ${server_hash}\n" > notes'
      env:
        version_code: ${{ needs.build_app.outputs.version_code }}
        app_hash: ${{ needs.build_app.outputs.hash }}
        server_hash: ${{ needs.build_server.outputs.hash }}
    - name: Create Github Release
      run: gh release create "v$VERSION" -d -F notes -t "v$VERSION" *.apk *.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ needs.build_app.outputs.version }}
