name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: audio-share-app
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - run: mkdir ~/.android && echo "$release_jks" | base64 -d > ~/.android/release.jks
      env:
        release_jks: ${{ secrets.RELEASE_JKS }}
        
    - run: chmod +x gradlew
    # - run: ./gradlew :app:assembleRelease
    - run: ./gradlew :app:signingReport
      env:
        store_pass: ${{ secrets.STORE_PASS }}
        key_alias: ${{ secrets.KEY_ALIAS }}
        key_pass: ${{ secrets.KEY_PASS }}
